// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: gRPC/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chitchat_Post_FullMethodName      = "/chitchat/post"
	Chitchat_Broadcast_FullMethodName = "/chitchat/broadcast"
)

// ChitchatClient is the client API for Chitchat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChitchatClient interface {
	Post(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*Empty, error)
	Broadcast(ctx context.Context, in *UserDetails, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatMessage], error)
}

type chitchatClient struct {
	cc grpc.ClientConnInterface
}

func NewChitchatClient(cc grpc.ClientConnInterface) ChitchatClient {
	return &chitchatClient{cc}
}

func (c *chitchatClient) Post(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chitchat_Post_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chitchatClient) Broadcast(ctx context.Context, in *UserDetails, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Chitchat_ServiceDesc.Streams[0], Chitchat_Broadcast_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserDetails, ChatMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chitchat_BroadcastClient = grpc.ServerStreamingClient[ChatMessage]

// ChitchatServer is the server API for Chitchat service.
// All implementations must embed UnimplementedChitchatServer
// for forward compatibility.
type ChitchatServer interface {
	Post(context.Context, *ChatMessage) (*Empty, error)
	Broadcast(*UserDetails, grpc.ServerStreamingServer[ChatMessage]) error
	mustEmbedUnimplementedChitchatServer()
}

// UnimplementedChitchatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChitchatServer struct{}

func (UnimplementedChitchatServer) Post(context.Context, *ChatMessage) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedChitchatServer) Broadcast(*UserDetails, grpc.ServerStreamingServer[ChatMessage]) error {
	return status.Error(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedChitchatServer) mustEmbedUnimplementedChitchatServer() {}
func (UnimplementedChitchatServer) testEmbeddedByValue()                  {}

// UnsafeChitchatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChitchatServer will
// result in compilation errors.
type UnsafeChitchatServer interface {
	mustEmbedUnimplementedChitchatServer()
}

func RegisterChitchatServer(s grpc.ServiceRegistrar, srv ChitchatServer) {
	// If the following call panics, it indicates UnimplementedChitchatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chitchat_ServiceDesc, srv)
}

func _Chitchat_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChitchatServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chitchat_Post_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChitchatServer).Post(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chitchat_Broadcast_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserDetails)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChitchatServer).Broadcast(m, &grpc.GenericServerStream[UserDetails, ChatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chitchat_BroadcastServer = grpc.ServerStreamingServer[ChatMessage]

// Chitchat_ServiceDesc is the grpc.ServiceDesc for Chitchat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chitchat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chitchat",
	HandlerType: (*ChitchatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "post",
			Handler:    _Chitchat_Post_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "broadcast",
			Handler:       _Chitchat_Broadcast_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gRPC/proto.proto",
}
